# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Corso Systems
email: info@corsosystems.com.com
description: > # this means to ignore newlines until "baseurl:"
  Corso Systems is a system integration firm based in Chicago Illinois. Founded in 2011, they focus on implementing business intelligence and process automation solutions for a wide variety of industries including oil & gas, food & beverage, solar power generation, and mining. Corso Systems prides itself on building long-term customer relationships, combining experience and tribal knowledge to build foundational systems that help drive innovation in how customers do business.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://corsosystems.com" # the base hostname & protocol for your site
twitter_username: corsosystems
github_username:  alexmarcy

# Build settings
markdown: kramdown
